# Generated by Django 3.1.5 on 2022-02-05 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, through='users.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
