# Generated by Django 3.1.5 on 2022-02-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user_who_liked', 'post_liked')},
        ),
    ]
